import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

interface colorProps {
  color: {
    hex?: string;
    rbg?: string;
    hsl?: string;
  };
}

export async function getStaticProps() {
  const res = await fetch("https://x-colors.herokuapp.com/api/random");

  const data = await res.json();
  const color = data;

  return {
    props: {
      color,
    },
  };
}

export default function Home({ color }: colorProps) {
  const [selectColor, setSelectColor] = useState(color);

  async function getNewColor() {
    const res = await fetch("https://x-colors.herokuapp.com/api/random");

    const data = await res.json();
    const color = data;

    setSelectColor(color);
  }

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;600&family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
    </div>
  );
}
