import Head from "next/head";
import Image from "next/image";

import { useState } from "react";

import GameLogs from "../shared/components/GameLogs";

import { Container } from "../styles/index";

interface colorProps {
  color: {
    hex?: string;
    rbg?: string;
    hsl?: string;
  };
}

export async function getStaticProps() {
  const res = await fetch("https://x-colors.herokuapp.com/api/random");

  const data = await res.json();
  const color = data;

  return {
    props: {
      color,
    },
  };
}

export default function Home({ color }: colorProps) {
  const [selectColor, setSelectColor] = useState(color);

  async function getNewColor() {
    const res = await fetch("https://x-colors.herokuapp.com/api/random");

    const data = await res.json();
    const color = data;

    setSelectColor(color);
  }

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <GameLogs />
      </Container>
    </div>
  );
}
