import Head from "next/head";

import React, { useState, createContext } from "react";

import SinglePage from "../modules/SinglePage";

interface GlobalContext {
  hasGameStarted: boolean;
  setGameStarted: React.Dispatch<React.SetStateAction<boolean>>;
}

export const Context = createContext<GlobalContext>({
  hasGameStarted: false,
  setGameStarted: () => {},
});

interface colorProps {
  color: {
    hex?: string;
    rbg?: string;
    hsl?: string;
  };
}

export async function getStaticProps() {
  const res = await fetch("https://x-colors.herokuapp.com/api/random");

  const data = await res.json();
  const color = data;

  return {
    props: {
      color,
    },
  };
}

export default function Home({ color }: colorProps) {
  const [hasGameStarted, setGameStarted] = useState(false);

  const [selectColor, setSelectColor] = useState(color);

  async function getNewColor() {
    const res = await fetch("https://x-colors.herokuapp.com/api/random");

    const data = await res.json();
    const color = data;

    setSelectColor(color);
  }

  return (
    <Context.Provider value={{ hasGameStarted, setGameStarted }}>
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <SinglePage />
      </div>
    </Context.Provider>
  );
}
